### ISSUE TITLE
Where can I find the focal length of the kitti dataset ？

### ISSUE THREAD

**Issue by YoucanBaby** [cleinc/bts#96]
Excuse me, where can I find the focal length of the kitti dataset ？Please tell me, thankkkkk you ！

**Comment by Xiaochaosui** [comment]
> Excuse me, where can I find the focal length of the kitti dataset ？Please tell me, thankkkkk you ！

嗨咯，同学，你找到这个Focal怎么算出来的了么？

**Comment by YoucanBaby** [comment]
> > Excuse me, where can I find the focal length of the kitti dataset ？Please tell me, thankkkkk you ！
> 
> 嗨咯，同学，你找到这个Focal怎么算出来的了么？

没有，放弃这个工作了。最近的新工作，比如depth-anything还不错。
